#!/usr/bin/env node
/**
 * Pulls design tokens from andrewkriley/design-system (shared.json +
 * business-venture.json — build4galileo's brand profile), resolves
 * `{path.to.token}` references per that repo's CONSUME.md, and writes
 * resolved CSS custom properties to
 * apps/chat-mvp/frontend/src/styles/tokens.css.
 *
 * Deliberately NOT run at build time or in CI: output is committed, and
 * this script is re-run manually when the upstream brand tokens change —
 * a token update becomes a normal reviewable diff, not something the
 * frontend build silently drifts on. Run from the repo root:
 *
 *   node scripts/sync-tokens.mjs
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_PATH = join(REPO_ROOT, "apps/chat-mvp/frontend/src/styles/tokens.css");

const RAW_BASE = "https://raw.githubusercontent.com/andrewkriley/design-system/main/design-system/tokens";
const SOURCES = ["shared.json", "business-venture.json"];
const CSS_VAR_PREFIX = "--b4g";

async function fetchTokenFile(name) {
  const response = await fetch(`${RAW_BASE}/${name}`);
  if (!response.ok) {
    throw new Error(`failed to fetch ${name}: HTTP ${response.status}`);
  }
  return response.json();
}

function isTokenLeaf(node) {
  return node !== null && typeof node === "object" && "value" in node;
}

function deepMerge(target, source) {
  for (const [key, value] of Object.entries(source)) {
    if (isTokenLeaf(value) || typeof value !== "object" || value === null) {
      target[key] = value;
    } else {
      target[key] = deepMerge(target[key] && typeof target[key] === "object" ? target[key] : {}, value);
    }
  }
  return target;
}

function getByPath(tree, path) {
  return path.split(".").reduce((node, key) => (node ? node[key] : undefined), tree);
}

function resolveValue(tree, value, seen = new Set()) {
  const match = typeof value === "string" && value.match(/^\{([\w.]+)\}$/);
  if (!match) {
    return value;
  }
  const refPath = match[1];
  if (seen.has(refPath)) {
    throw new Error(`circular token reference: ${[...seen, refPath].join(" -> ")}`);
  }
  const target = getByPath(tree, refPath);
  if (!isTokenLeaf(target)) {
    throw new Error(`unresolved token reference: {${refPath}}`);
  }
  return resolveValue(tree, target.value, new Set([...seen, refPath]));
}

function toKebabSegment(segment) {
  return segment.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function flattenToCssVars(tree, prefixParts, tree_root, out) {
  for (const [key, node] of Object.entries(tree)) {
    const nextParts = [...prefixParts, toKebabSegment(key)];
    if (isTokenLeaf(node)) {
      const varName = `${CSS_VAR_PREFIX}-${nextParts.join("-")}`;
      out.push([varName, resolveValue(tree_root, node.value)]);
    } else if (typeof node === "object" && node !== null) {
      flattenToCssVars(node, nextParts, tree_root, out);
    }
  }
  return out;
}

async function main() {
  const files = await Promise.all(SOURCES.map(fetchTokenFile));
  const merged = files.reduce((acc, file) => deepMerge(acc, file), {});
  const cssVars = flattenToCssVars(merged, [], merged, []);

  const lines = [
    "/* AUTO-GENERATED by scripts/sync-tokens.mjs — do not edit by hand. */",
    "/* Source: andrewkriley/design-system tokens/{shared,business-venture}.json */",
    ":root {",
    ...cssVars.map(([name, value]) => `  ${name}: ${value};`),
    "}",
    "",
  ];

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, lines.join("\n"), "utf8");
  console.log(`Wrote ${cssVars.length} tokens to ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
